### ISSUE TITLE
Add Calcified rocks

### ISSUE THREAD

**Issue by hispazn** [a-h-designs/Advanced-Mining#1]
Varlamore update introduce Calcified Rocks to mine

**Comment by a-h-designs** [comment]
I'm currently working on adding it to the plugin.

I will update when I have added it and waiting it for the plugin to be updated on runelite.

**Comment by a-h-designs** [comment]
Full support for Blessed Bone Shards and Calcified Deposits have been added. Just waiting for it to be review and updated for everyone.
