### ISSUE TITLE
Display potential prayer xp from calcified bone shards

### ISSUE THREAD

**Issue by vmgi** [a-h-designs/Advanced-Mining#2]
Along with displaying the number of bone shards received from calcified rocks, display the potential prayer xp ie:
prayer xp(blessed wine): (num_boneshards * 5)
prayer xp(blessed sunfire wine):  (num_boneshards * 6)

**Comment by a-h-designs** [comment]
Sorry it's taken a while for me to get to reading this. I will look into this and see about adding it in for you.

**Comment by a-h-designs** [comment]
I have added this to the Plugin. It hopefully will be updated soon.
